[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "futures-glib"
version = "0.1.0"

[dependencies]
futures = "0.1"
libc = "^0.2.2"
slab = "^0.3.0"
glib-sys = { version = "0.3", features = ["v2_36"] }
