[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "futures-glib"
version = "0.1.0"

[dependencies]
bytes = "^0.4.2"
futures = "^0.1.14"
libc = "^0.2.2"
net2 = "0.2"
slab = "^0.3.0"
tokio-core = { path = "/home/bouanto/Telechargements/Source/tokio-core" }
tokio-io = "0.1"
winapi = "^0.2.8"

[dependencies.glib-sys]
features = ["v2_36"]
version = "0.3"

[dev-dependencies]
gtk = "0.1"

[features]
nightly = []
