[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "futures-glib"
version = "0.1.0"

[dependencies]
futures = "0.1"
libc = "^0.2.2"
slab = "^0.3.0"

[dependencies.glib-sys]
features = ["v2_36"]
version = "0.3"

[dev-dependencies]
gtk = "^0.1.2"
