[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "futures-glib"
version = "0.1.0"

[dependencies]
futures = { git = "https://github.com/alexcrichton/futures-rs", branch = "spawn-trait" }
libc = "^0.2.2"
slab = "^0.3.0"
glib-sys = { version = "0.3", features = ["v2_36"] }
net2 = "0.2"
tokio-io = "0.1"

[dev-dependencies]
gtk = "0.1"

[replace]
"futures:0.1.13" = { git = "https://github.com/alexcrichton/futures-rs", branch = "spawn-trait" }
