version: 2
jobs:
    build:
        working_directory: ~/source
        docker:
            - image: scorpil/rust:1.18
        steps:
            - checkout
            - run: apt-get install libgtk-3-dev
            - run: cargo test
